name: "Add Liquidity"

env:
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
  MNEMONIC: ${{ secrets.MNEMONIC }}

on:
  workflow_dispatch:
    inputs:
      hifi-pool:
        description: "Pool address"
        required: true
      underlying-amount:
        description: "Underlying amount"
        required: true
      chain:
        description: "Chain name in lowercase"
        required: true
      h-token-ratio:
        description: "Htoken ratio"
        required: true
      hifi-proxy-target:
        description: "Hifi proxy target address"
        required: true
      ref:
        default: "main"
        description: "Git ref to checkout"
        required: false

jobs:
  add-liquidity:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: "Setup Node.js"
        uses: "actions/setup-node@v2"
        with:
          cache: "yarn"
          node-version: "16"

      - name: "Install dependencies"
        run: "yarn install --immutable"

      - name: "Build packages"
        run: "yarn build"

      - name: "Compile the contracts and generate TypeChain bindings"
        run: "yarn workspace @hifi/amm typechain"

      - name: "Add liquidity"
        id: "deploy"
        run: >-
          yarn workspace @hifi/deployers hardhat 
          init:pool:add-liquidity --network "${{ github.event.inputs.chain }}"
          --hifi-pool "${{ github.event.inputs.hifi-pool }}"
          --underlying-amount "${{ github.event.inputs.underlying-amount }}"
          --h-token-ratio "${{ github.event.inputs.h-token-ratio }}"
          --hifi-proxy-target "${{ github.event.inputs.hifi-proxy-target }}"
