name: "Continuous Integration"

env:
  COVERAGE_GIT_BRANCH: "main"
  COVERAGE_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
  COVERAGE_SERVICE_NAME: "github-actions-ci"
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
  MNEMONIC: ${{ secrets.MNEMONIC }}

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  diff:
    runs-on: ubuntu-latest
    outputs:
      amm: ${{ steps.filter.outputs["amm"] }}
      flash-swap: ${{ steps.filter.outputs["flash-swap"] }}
      protocol: ${{ steps.filter.outputs["protocol"] }}
      proxy-target: ${{ steps.filter.outputs["proxy-target"] }}
    steps:
      - uses: dorny/paths-filter@v2
        id: diff
        with:
          base: "main"
          filters: |
            amm:
              - "packages/amm/**"
            flash-swap:
              - "packages/flash-swap/**"
            protocol:
              - "packages/protocol/**"
            proxy-target:
              - "packages/proxy-target/**"

  ci-amm:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"

      - name: "Install Node.js"
        uses: "actions/setup-node@v2"
        with:
          cache: "yarn"
          node-version: "16"

      - name: "Install dependencies"
        run: "yarn workspace @hifi/amm install --immutable"

      - name: "Build packages"
        run: "yarn build"

      - name: "Lint Solidity and TypeScript code"
        run: "yarn workspace @hifi/amm lint"

      - name: "Compile the contracts and generate TypeChain bindings"
        run: "yarn workspace @hifi/amm typechain"

      - name: "Test the contracts and run test coverage"
        run: "yarn workspace @hifi/amm coverage"

      - name: "Upload coverage report to Coveralls"
        uses: "coverallsapp/github-action@master"
        with:
          flag-name: "amm"
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          parallel: true
          path-to-lcov: "./packages/amm/coverage/lcov.info"

  ci-flash-swap:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"

      - name: "Install Node.js"
        uses: "actions/setup-node@v2"
        with:
          cache: "yarn"
          node-version: "16"

      - name: "Install dependencies"
        run: "yarn workspace @hifi/flash-swap install --immutable"

      - name: "Build packages"
        run: "yarn build"

      - name: "Lint Solidity and TypeScript code"
        run: "yarn workspace @hifi/flash-swap lint"

      - name: "Compile the contracts and generate TypeChain bindings"
        run: "yarn workspace @hifi/flash-swap typechain"

      - name: "Test the contracts and run test coverage"
        run: "yarn workspace @hifi/flash-swap coverage"

      - name: "Upload coverage report to Coveralls"
        uses: "coverallsapp/github-action@master"
        with:
          flag-name: "flash-swap"
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          parallel: true
          path-to-lcov: "./packages/flash-swap/coverage/lcov.info"

  ci-protocol:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"

      - name: "Install Node.js"
        uses: "actions/setup-node@v2"
        with:
          cache: "yarn"
          node-version: "16"

      - name: "Install dependencies"
        run: "yarn workspace @hifi/protocol install --immutable"

      - name: "Build packages"
        run: "yarn build"

      - name: "Lint Solidity and TypeScript code"
        run: "yarn workspace @hifi/protocol lint"

      - name: "Compile the contracts and generate TypeChain bindings"
        run: "yarn workspace @hifi/protocol typechain"

      - name: "Test the contracts and run test coverage"
        run: "yarn workspace @hifi/protocol coverage"

      - name: "Upload coverage report to Coveralls"
        uses: "coverallsapp/github-action@master"
        with:
          flag-name: "protocol"
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          parallel: true
          path-to-lcov: "./packages/protocol/coverage/lcov.info"

  ci-proxy-target:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"

      - name: "Install Node.js"
        uses: "actions/setup-node@v2"
        with:
          cache: "yarn"
          node-version: "16"

      - name: "Install dependencies"
        run: "yarn install --immutable"

      - name: "Build packages"
        run: "yarn build"

      - name: "Lint Solidity and TypeScript code"
        run: "yarn workspace @hifi/proxy-target lint"

      - name: "Compile the contracts and generate TypeChain artifacts"
        run: "yarn workspace @hifi/proxy-target typechain"

  finish:
    needs:
      - ci-amm
      - ci-flash-swap
      - ci-protocol
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          parallel-finished: true
