name: "Deploy: StablecoinPriceFeed"

env:
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
  MNEMONIC: ${{ secrets.MNEMONIC }}

on:
  workflow_dispatch:
    inputs:
      chain:
        description: "Chain name in lowercase"
        required: true
      confirmations:
        default: "2"
        description: "Number of block confirmations to wait before attempting verification"
        required: false
      description:
        description: "Description of the price feed, e.g. 'USDC/USD'"
        required: true
      price:
        description: "Immutable price of the stablecoin, with 8 decimals of precision"
        required: true

jobs:
  deploy-and-verify:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"

      - name: "Setup Node.js"
        uses: "actions/setup-node@v2"
        with:
          cache: "yarn"
          node-version: "16"

      - name: "Install dependencies"
        run: "yarn install --immutable"

      - name: "Build packages"
        run: "yarn build"

      - name: "Deploy StablecoinPriceFeed"
        run: >-
          yarn workspace @hifi/deployers hardhat
          deploy:contract:stablecoin-price-feed --network "${{ github.event.inputs.chain }}"
          --description "${{ github.event.inputs.description }}"
          --price "${{ github.event.inputs.price }}"
          --confirmations "${{ github.event.inputs.confirmations }}"
          --set-output true

      - name: "Compile the contracts and generate TypeChain bindings"
        run: "yarn workspace @hifi/protocol typechain"

      - name: "Verify StablecoinPriceFeed"
        run: >-
          yarn workspace @hifi/protocol hardhat
          verify "${{ steps.deploy.outputs.stablecoin-price-feed }}" --network "${{ github.event.inputs.chain }}"
          --description "${{ github.event.inputs.description }}"
          --price "${{ github.event.inputs.price }}"
