name: "Deploy: HToken"

env:
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
  MNEMONIC: ${{ secrets.MNEMONIC }}

on:
  workflow_dispatch:
    inputs:
      balance_sheet:
        description: "Address of the BalanceSheet contract"
        required: true
      chain:
        description: "Chain name in lowercase"
        required: true
      maturity:
        description: "Unix timestamp for when the hToken matures"
        required: true
      name:
        description: "ERC-20 name of the hToken"
        required: true
      symbol:
        description: "ERC-20 symbol of the hToken"
        required: true
      underlying:
        description: "Address of the underlying ERC-20 contract"
        required: true

jobs:
  deploy-h-token:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"

      - name: "Setup Node.js"
        uses: "actions/setup-node@v2"
        with:
          cache: "yarn"
          node-version: "16"

      - name: "Install dependencies"
        run: "yarn install --immutable"

      - name: "Build packages"
        run: "yarn build"

      - name: "Deploy HToken"
        run: >-
          yarn workspace @hifi/deployers hardhat
          deploy:HToken --network "${{ github.event.inputs.chain }}"
          --balance-sheet "${{ github.event.inputs.balance_sheet }}"
          --maturity "${{ github.event.inputs.maturity }}"
          --name "${{ github.event.inputs.name }}"
          --symbol "${{ github.event.inputs.symbol }}"
          --underlying "${{ github.event.inputs.underlying }}"
