name: "Deploy: Protocol"

env:
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
  MNEMONIC: ${{ secrets.MNEMONIC }}

on:
  workflow_dispatch:
    inputs:
      balance-sheet:
        description: "Address of the BalanceSheet contract"
        required: true
      chain:
        description: "Chain name in lowercase"
        required: true
      confirmations:
        default: "2"
        description: "Number of block confirmations to wait before attempting verification"
        required: false
      h-token-maturity:
        description: "Unix timestamp for when the hToken matures"
        required: true
      h-token-name:
        description: "ERC-20 name of the hToken"
        required: true
      h-token-symbol:
        description: "ERC-20 symbol of the hToken"
        required: true
      hifi-pool-name:
        description: "ERC-20 name of the pool"
        required: true
      hifi-pool-symbol:
        description: "ERC-20 symbol of the pool"
        required: true
      underlying:
        description: "Address of the underlying ERC-20 contract"
        required: true

jobs:
  deploy-and-verify:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"

      - name: "Setup Node.js"
        uses: "actions/setup-node@v2"
        with:
          cache: "yarn"
          node-version: "16"

      - name: "Install dependencies"
        run: "yarn install --immutable"

      - name: "Build packages"
        run: "yarn build"

      - name: "Deploy protocol"
        run: >-
          yarn workspace @hifi/deployers hardhat
          deploy:protocol --network "${{ github.event.inputs.chain }}"
          --balance-sheet "${{ github.event.inputs.balance-sheet }}"
          --h-token-maturity "${{ github.event.inputs.h-token-maturity }}"
          --h-token-name "${{ github.event.inputs.h-token-name }}"
          --h-token-symbol "${{ github.event.inputs.h-token-symbol }}"
          --hifi-pool-name "${{ github.event.inputs.hifi-pool-name }}"
          --hifi-pool-symbol "${{ github.event.inputs.hifi-pool-symbol }}"
          --underlying "${{ github.event.inputs.underlying }}"
          --confirmations "${{ github.event.inputs.confirmations }}"
          --set-output true
