name: "Deploy: ChainlinkOperator"

env:
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
  MNEMONIC: ${{ secrets.MNEMONIC }}

on:
  workflow_dispatch:
    inputs:
      chain:
        description: "Chain name in lowercase"
        required: true
      confirmations:
        default: "2"
        description: "Number of block confirmations to wait before attempting verification"
        required: false
      ref:
        default: "main"
        description: "Git ref to checkout"
        required: false

jobs:
  deploy-and-verify:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: "Setup Node.js"
        uses: "actions/setup-node@v2"
        with:
          cache: "yarn"
          node-version: "16"

      - name: "Install dependencies"
        run: "yarn install --immutable"

      - name: "Build packages"
        run: "yarn build"

      - name: "Deploy ChainlinkOperator"
        id: "deploy"
        run: >-
          yarn workspace @hifi/deployers hardhat
          deploy:contract:chainlink-operator --network "${{ github.event.inputs.chain }}"
          --confirmations "${{ github.event.inputs.confirmations }}"
          --set-output true

      - name: "Compile the contracts and generate TypeChain bindings"
        run: "yarn workspace @hifi/protocol typechain"

      - name: "Verify ChainlinkOperator"
        run: >-
          yarn workspace @hifi/protocol hardhat
          verify "${{ steps.deploy.outputs.chainlink-operator }}" --network "${{ github.event.inputs.chain }}"
