name: "Deploy: HifiPool"

env:
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
  MNEMONIC: ${{ secrets.MNEMONIC }}

on:
  workflow_dispatch:
    inputs:
      chain:
        description: "Chain name in lowercase"
        required: true
      h_token:
        description: "Address of the hToken contract"
        required: true
      name:
        description: "ERC-20 name of the pool"
        required: true
      symbol:
        description: "ERC-20 symbol of the pool"
        required: true

jobs:
  deploy-hifi-pool:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"

      - name: "Setup Node.js"
        uses: "actions/setup-node@v2"
        with:
          cache: "yarn"
          node-version: "16"

      - name: "Install dependencies"
        run: "yarn install --immutable"

      - name: "Build packages"
        run: "yarn build"

      - name: "Deploy HifiPool"
        run: >-
          yarn workspace @hifi/deployers hardhat
          deploy:HifiPool --network "${{ github.event.inputs.chain }}"
          --h-token "${{ github.event.inputs.h_token }}"
          --name "${{ github.event.inputs.name }}"
          --symbol "${{ github.event.inputs.symbol }}"
