name: "Integration: TypeScript Packages"

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  diff:
    runs-on: ubuntu-latest
    outputs:
      constants: ${{ steps.diff.outputs.constants }}
      helpers: ${{ steps.diff.outputs.helpers }}
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"
      - name: "Diff the files"
        uses: dorny/paths-filter@v2
        id: diff
        with:
          base: "main"
          filters: |
            constants:
              - "packages/constants/**"
            helpers:
              - "packages/helpers/**"

  integration-constants:
    if: ${{ needs.diff.outputs.constants == 'true' }}
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"

      - name: "Install Node.js"
        uses: "actions/setup-node@v2"
        with:
          cache: "yarn"
          node-version: "16"

      - name: "Install the dependencies"
        run: "yarn install --immutable"

      - name: "Lint the code"
        run: "yarn workspace @hifi/constants lint"

      - name: "Build the package"
        run: "yarn workspace @hifi/constants build"

  integration-helpers:
    if: ${{ needs.diff.outputs.helpers == 'true' }}
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"

      - name: "Install Node.js"
        uses: "actions/setup-node@v2"
        with:
          cache: "yarn"
          node-version: "16"

      - name: "Install the dependencies"
        run: "yarn install --immutable"

      - name: "Lint the code"
        run: "yarn workspace @hifi/helpers lint"

      - name: "Build the package"
        run: "yarn workspace @hifi/helpers build"
